// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeRdDrQZVmTeShzvrf1w4Cd7mgxSVYmAU',
    appId: '1:1081569675869:web:2f4d7ebc9bc38d6f619bb4',
    messagingSenderId: '1081569675869',
    projectId: 'flutter-chart-app-5a088',
    authDomain: 'flutter-chart-app-5a088.firebaseapp.com',
    storageBucket: 'flutter-chart-app-5a088.appspot.com',
    measurementId: 'G-B3WFZB5K5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPxlyQJsu196JAY2SVUp6HV9P3kw2Rhao',
    appId: '1:1081569675869:android:9992b036fc1df2e3619bb4',
    messagingSenderId: '1081569675869',
    projectId: 'flutter-chart-app-5a088',
    storageBucket: 'flutter-chart-app-5a088.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXrFAxwv3ScmRDl3sdCIS5nZeorvRycFk',
    appId: '1:1081569675869:ios:d02653b745433c00619bb4',
    messagingSenderId: '1081569675869',
    projectId: 'flutter-chart-app-5a088',
    storageBucket: 'flutter-chart-app-5a088.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXrFAxwv3ScmRDl3sdCIS5nZeorvRycFk',
    appId: '1:1081569675869:ios:b60f68a6085791dc619bb4',
    messagingSenderId: '1081569675869',
    projectId: 'flutter-chart-app-5a088',
    storageBucket: 'flutter-chart-app-5a088.appspot.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
